set_property PACKAGE_PIN K16 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN J16 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN G18 [get_ports {GPIO_0_0_tri_io[2]}]
set_property PACKAGE_PIN G17 [get_ports {GPIO_0_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN C20 [get_ports {RGMII_0_td[1]}]
set_property PACKAGE_PIN E19 [get_ports RGMII_0_tx_ctl]
set_property PACKAGE_PIN D20 [get_ports {RGMII_0_td[3]}]
set_property PACKAGE_PIN B20 [get_ports {RGMII_0_td[0]}]
set_property PACKAGE_PIN D18 [get_ports {RGMII_0_rd[2]}]
set_property PACKAGE_PIN F20 [get_ports MDIO_PHY_0_mdio_io]
set_property PACKAGE_PIN F19 [get_ports MDIO_PHY_0_mdc]
set_property PACKAGE_PIN D19 [get_ports {RGMII_0_td[2]}]
set_property PACKAGE_PIN B19 [get_ports {RGMII_0_rd[3]}]
set_property PACKAGE_PIN F17 [get_ports {RGMII_0_rd[0]}]
set_property PACKAGE_PIN A20 [get_ports RGMII_0_txc]
set_property PACKAGE_PIN J18 [get_ports RGMII_0_rxc]
set_property PACKAGE_PIN E17 [get_ports RGMII_0_rx_ctl]
set_property PACKAGE_PIN E18 [get_ports {RGMII_0_rd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports MDIO_PHY_0_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports MDIO_PHY_0_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_txc]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_rx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[1]}]


create_clock -period 8.000 -name RGMII_0_rxc -waveform {0.000 4.000} [get_ports RGMII_0_rxc]
set_clock_groups -logically_exclusive -group [get_clocks -include_generated_clocks {gmii_clk_25m_out gmii_clk_2_5m_out}] -group [get_clocks -include_generated_clocks gmii_clk_125m_out]

set_property SLEW FAST [get_ports {RGMII_0_td[0]}]
set_property SLEW FAST [get_ports {RGMII_0_td[1]}]
set_property SLEW FAST [get_ports {RGMII_0_td[2]}]
set_property SLEW FAST [get_ports {RGMII_0_td[3]}]
set_property SLEW FAST [get_ports RGMII_0_tx_ctl]
set_property SLEW FAST [get_ports RGMII_0_txc]

set_property SLEW FAST [get_ports MDIO_PHY_0_mdc]
set_property SLEW FAST [get_ports MDIO_PHY_0_mdio_io]