# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# Block Designs: bd/ZYNQ_CORE/ZYNQ_CORE.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE || ORIG_REF_NAME==ZYNQ_CORE} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_processing_system7_0_0/ZYNQ_CORE_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_processing_system7_0_0 || ORIG_REF_NAME==ZYNQ_CORE_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_gmii_to_rgmii_0_0/ZYNQ_CORE_gmii_to_rgmii_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_gmii_to_rgmii_0_0 || ORIG_REF_NAME==ZYNQ_CORE_gmii_to_rgmii_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_util_vector_logic_0_0/ZYNQ_CORE_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_util_vector_logic_0_0 || ORIG_REF_NAME==ZYNQ_CORE_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_doGain_0_0/ZYNQ_CORE_doGain_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_doGain_0_0 || ORIG_REF_NAME==ZYNQ_CORE_doGain_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_dma_0_0/ZYNQ_CORE_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_axi_dma_0_0 || ORIG_REF_NAME==ZYNQ_CORE_axi_dma_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_ps7_0_axi_periph_0/ZYNQ_CORE_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_ps7_0_axi_periph_0 || ORIG_REF_NAME==ZYNQ_CORE_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_rst_ps7_0_200M_0/ZYNQ_CORE_rst_ps7_0_200M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_rst_ps7_0_200M_0 || ORIG_REF_NAME==ZYNQ_CORE_rst_ps7_0_200M_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_xbar_0/ZYNQ_CORE_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_xbar_0 || ORIG_REF_NAME==ZYNQ_CORE_xbar_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_mem_intercon_0/ZYNQ_CORE_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_axi_mem_intercon_0 || ORIG_REF_NAME==ZYNQ_CORE_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_xlconcat_0_0/ZYNQ_CORE_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_xlconcat_0_0 || ORIG_REF_NAME==ZYNQ_CORE_xlconcat_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_auto_pc_0/ZYNQ_CORE_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_auto_pc_0 || ORIG_REF_NAME==ZYNQ_CORE_auto_pc_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_auto_us_0/ZYNQ_CORE_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_auto_us_0 || ORIG_REF_NAME==ZYNQ_CORE_auto_us_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_auto_us_1/ZYNQ_CORE_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_auto_us_1 || ORIG_REF_NAME==ZYNQ_CORE_auto_us_1} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_auto_pc_1/ZYNQ_CORE_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_auto_pc_1 || ORIG_REF_NAME==ZYNQ_CORE_auto_pc_1} -quiet] -quiet

# XDC: d:/Smart_ZYNQ_7010/Ubuntu_AXI_Stream_test/Ubuntu_AXI_Stream_test.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_processing_system7_0_0/ZYNQ_CORE_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_processing_system7_0_0 || ORIG_REF_NAME==ZYNQ_CORE_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Smart_ZYNQ_7010/Ubuntu_AXI_Stream_test/Ubuntu_AXI_Stream_test.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_gmii_to_rgmii_0_0/synth/ZYNQ_CORE_gmii_to_rgmii_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_gmii_to_rgmii_0_0 || ORIG_REF_NAME==ZYNQ_CORE_gmii_to_rgmii_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Smart_ZYNQ_7010/Ubuntu_AXI_Stream_test/Ubuntu_AXI_Stream_test.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_gmii_to_rgmii_0_0/synth/ZYNQ_CORE_gmii_to_rgmii_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_gmii_to_rgmii_0_0 || ORIG_REF_NAME==ZYNQ_CORE_gmii_to_rgmii_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Smart_ZYNQ_7010/Ubuntu_AXI_Stream_test/Ubuntu_AXI_Stream_test.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_gmii_to_rgmii_0_0/synth/ZYNQ_CORE_gmii_to_rgmii_0_0_ooc.xdc

# XDC: d:/Smart_ZYNQ_7010/Ubuntu_AXI_Stream_test/Ubuntu_AXI_Stream_test.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_doGain_0_0/constraints/doGain_ooc.xdc

# XDC: d:/Smart_ZYNQ_7010/Ubuntu_AXI_Stream_test/Ubuntu_AXI_Stream_test.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_dma_0_0/ZYNQ_CORE_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_axi_dma_0_0 || ORIG_REF_NAME==ZYNQ_CORE_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Smart_ZYNQ_7010/Ubuntu_AXI_Stream_test/Ubuntu_AXI_Stream_test.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_dma_0_0/ZYNQ_CORE_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_axi_dma_0_0 || ORIG_REF_NAME==ZYNQ_CORE_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Smart_ZYNQ_7010/Ubuntu_AXI_Stream_test/Ubuntu_AXI_Stream_test.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_rst_ps7_0_200M_0/ZYNQ_CORE_rst_ps7_0_200M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_rst_ps7_0_200M_0 || ORIG_REF_NAME==ZYNQ_CORE_rst_ps7_0_200M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Smart_ZYNQ_7010/Ubuntu_AXI_Stream_test/Ubuntu_AXI_Stream_test.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_rst_ps7_0_200M_0/ZYNQ_CORE_rst_ps7_0_200M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_rst_ps7_0_200M_0 || ORIG_REF_NAME==ZYNQ_CORE_rst_ps7_0_200M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Smart_ZYNQ_7010/Ubuntu_AXI_Stream_test/Ubuntu_AXI_Stream_test.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_auto_pc_0/ZYNQ_CORE_auto_pc_0_ooc.xdc

# XDC: d:/Smart_ZYNQ_7010/Ubuntu_AXI_Stream_test/Ubuntu_AXI_Stream_test.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_auto_us_0/ZYNQ_CORE_auto_us_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_auto_us_0 || ORIG_REF_NAME==ZYNQ_CORE_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Smart_ZYNQ_7010/Ubuntu_AXI_Stream_test/Ubuntu_AXI_Stream_test.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_auto_us_0/ZYNQ_CORE_auto_us_0_ooc.xdc

# XDC: d:/Smart_ZYNQ_7010/Ubuntu_AXI_Stream_test/Ubuntu_AXI_Stream_test.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_auto_us_1/ZYNQ_CORE_auto_us_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_auto_us_1 || ORIG_REF_NAME==ZYNQ_CORE_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Smart_ZYNQ_7010/Ubuntu_AXI_Stream_test/Ubuntu_AXI_Stream_test.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_auto_us_1/ZYNQ_CORE_auto_us_1_ooc.xdc

# XDC: d:/Smart_ZYNQ_7010/Ubuntu_AXI_Stream_test/Ubuntu_AXI_Stream_test.gen/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_auto_pc_1/ZYNQ_CORE_auto_pc_1_ooc.xdc

# XDC: d:/Smart_ZYNQ_7010/Ubuntu_AXI_Stream_test/Ubuntu_AXI_Stream_test.gen/sources_1/bd/ZYNQ_CORE/ZYNQ_CORE_ooc.xdc
